# Generated by Django 2.2.2 on 2019-06-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_auto_20190626_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='content',
            new_name='cardTitle',
        ),
        migrations.AddField(
            model_name='card',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
