# Generated by Django 2.2.2 on 2019-06-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_auto_20190626_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Description',
            new_name='description',
        ),
    ]
