# Generated by Django 2.2.2 on 2019-06-27 20:44

from django.db import migrations
import sort_order_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_auto_20190626_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['cardSort']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['listSort']},
        ),
        migrations.AddField(
            model_name='card',
            name='cardSort',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='listSort',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0),
        ),
    ]
