# Generated by Django 2.2.2 on 2019-06-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0005_auto_20190627_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='background_color',
            field=models.TextField(null=True),
        ),
    ]
