# Generated by Django 2.2.2 on 2019-06-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0006_title_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backgroundcolor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='title',
            name='background_color',
        ),
    ]
