# Generated by Django 2.2.2 on 2019-06-28 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0007_auto_20190628_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trello.Card'),
        ),
    ]
